### ISSUE TITLE
how can be search on field?

### ISSUE THREAD

**Issue by dnypinkesh** [bcrowe/cakephp-encrypted-type#1]
how can we implement search on that encrypted field???

**Comment by bcrowe** [comment]
Hi @dnypinkesh,

So that's a bit of a problem whenever the actual values in a database column are encrypted. (application-level). If you need your data to be searchable and also encrypted, I would explore full-disk or database-level encryption. I linked to this article: https://www.percona.com/blog/2016/04/08/mysql-data-at-rest-encryption/ in the README if you want to read the pros/cons of each approach yourself. Although, push come to shove, I guess you *could* encrypt the input before supplying it to the WHERE clause if you want a strict equality search, but you'll definitely have to be mindful about its performance and how that would scale.

**Comment by bcrowe** [comment]
Probably too late, but some discussion in the Cake Slack channel just had me revisit this. I butchered this answer. What I meant to say is, you could _hash_ the same value alongside the encrypted value, so that you have it available in plaintext, and also something consistent to compare/search against.
